resources:
  - name: myAppRepo
    type: GitRepo
    configuration:
      path: roja03/cicd-sample
      gitProvider: sampleCICD
      branches:
        include: master
pipelines:
  - name: pipeline_hello_world
    steps:
      - name: bld_backend
        type: MvnBuild
        configuration:
          mvnCommand: clean install -ntp
          configFileLocation: .
          inputResources:
            - name: myGitRepo
          integrations:
            - name: Artifactory
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "11"
        execution:
          onStart:
            - javac -version