resources:
  - name: myGitRepoo
    type: GitRepo
    configuration:
      gitProvider: sampleCICD
      path: roja03/cicd-sample
      branches:
        include: master
  - name: myBuildInfoo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: SampleApp
      buildNumber: 1
pipelines:
  - name: basic_pipeline_sample
    configuration:
      environmentVariables:
        readOnly:
          my_env_var: "hello"
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: myGitRepoo
          outputResources:
            - name: myBuildInfoo
        execution:
          onExecute:
            - echo $my_env_var
            - if [ -z $app_version ]; then add_pipeline_variables app_version=1.0.0; else app_version=$(bump_semver $app_version minor); fi
            - write_output myBuildInfoo "buildNumber=$app_version"
            - add_run_variables run_var="hello"
      - name: step_2
        type: Bash
        configuration:
          inputResources:
            - name: myBuildInfoo
          runtime:
            type: image
            image:
              auto:
                language: java
                versions: ['11']
        execution:
          onExecute:
            - echo $run_var
            - echo $res_myBuildInfoo_buildNumber

      - name: step_3
        type: Bash
        configuration:
          environmentVariables:
            step_env_var1: "hello"
          inputSteps:
            - name: step_2
        execution:
          onExecute:
            - echo $step_env_var1

      - name: step_4
        type: Bash
        configuration:
          inputSteps:
            - name: step_2
        execution:
          onExecute:
            - echo $app_version
      - name: step_5
        type: Bash
        configuration:
          inputSteps:
            - name: step_3
            - name: step_4
          integrations:
            - name: sampleCICD
        execution:
          onExecute:
            - 'curl -H "Authorization: token ${int_sampleCICD_token}" ${int_sampleCICD_url}/rate_limit' #int